### ISSUE TITLE
LibEGL

### ISSUE THREAD

**Issue by ejg3855** [KalebKE/ME7Tuner#10]
Not 100% sure what I am doing wrong, but I get this error everytime I try to run.

Using Java 8

libEGL warning: DRI2: failed to authenticate

**Comment by ejg3855** [comment]
Looks like its a 3d acceleration issue in my Ubuntu VM.

**Comment by alexandre88110** [comment]
bonjour jai un boitier mpps 16v et je voudrai faire une desactivation sur ma c5 2l0 hdi 140cv et jarive pas a trouver? car je vien seulement de lacheter et jai aussi une 307 1l6 hdi 90 cv et jaimerait reprogrammer niveau puissance et desactiver la vane egr

**Comment by alexandre88110** [comment]
sur la c5 desactiver fap et egr

**Comment by KalebKE** [comment]
Fixed in v1.0.
