### ISSUE TITLE
Wont Work on Win 10

### ISSUE THREAD

**Issue by xXxCryxXx** [KalebKE/ME7Tuner#12]
Hello

This tool wont work on Windows 10 i dont know what im doing wrong but the exe jar file opens in process mangaer but nothing happen no window nothing only 32% of CPU usage, no message nothing

**Comment by KalebKE** [comment]
Hi,

You need to have Java 8 installed (you probably have Java 11). I am currently working on getting everything updated to Java 11.

**Comment by KalebKE** [comment]
Java 17 support has been added in v1.0.
