### ISSUE TITLE
Unable to load map definitions.

### ISSUE THREAD

**Issue by allyouaskfor** [KalebKE/ME7Tuner#18]
Using Windows 10 I am not able to load each individual map definition. I successfully load the binary and matching XDF file and clicking the "select definition" button for each map it shows that it is able to locate them within the binary but after clicking "set", the definition remains undefined.
![Capture](https://user-images.githubusercontent.com/19245833/164997666-fb4afb5f-f075-4e4f-b43d-2ea5f84aa8bf.PNG)

Edit: I am having the same issue on my 2015 Macbook Air running Big Sur.

**Comment by KalebKE** [comment]
@allyouaskfor 

Can you kindly provide your XDF file and binary? I will take a look.

**Comment by allyouaskfor** [comment]
Here is a zip containing the binary along with XDF. 
[allyouaskfor-ME7Tuner.zip](https://github.com/KalebKE/ME7Tuner/files/8550617/allyouaskfor-ME7Tuner.zip)

**Comment by KalebKE** [comment]
@allyouaskfor 

Thank you. I should have time to look at it this week.

**Comment by run4x** [comment]
Could this be related to regional settings? Dot vs comma as decimal separator.

I tried v1.0.3 on MBP (Monterey) and on Win10, both with non-US region and had similar issue as @allyouaskfor 
Then did a quick check on Win11 with US region and was able to set the maps in configuration.

With v1.0.4 I can select and set maps from xdf, but cannot open most of the tabs.

**Comment by KalebKE** [comment]
@run4x 

Thanks for that information. I'll take a look. I may not be setting a default local XML parser.

**Comment by KalebKE** [comment]
@allyouaskfor 

I see the issue. I haven't implemented functionality for the 'scalar link'. Your XDF is the first I have seen where this is used.

The tag for scalar link will embed in an  <XDFAXIS> tag... something like:

<embedinfo type="3" linkobjid="0x314C" />

However, some of your <XDFAXIS> tags are also embedded with the pure internal axis tag which looks like:

<EMBEDDEDDATA mmedtypeflags="0x02" mmedaddress="0x139AA" mmedelementsizebits="16" mmedcolcount="12" mmedmajorstridebits="16" mmedminorstridebits="0" />

The <embedinfo> tag ends up pointing to what effectively another table definition that I need to parse to eventually get to the desired axis.

It seems like the expected behavior here is that the <embedinfo> exists it overrides the pure internal axis? e.g, if you have a scalar link defined you expect it to defer to that address and ignore the pure internal address? It appears that tuner pro works this way.

**Comment by KalebKE** [comment]
@allyouaskfor 

There seems to be some junk conversions in the XDF file as well:   <MATH equation="0.114843.375 * X"> where '0.114843.375' is not a number.

<XDFCONSTANT uniqueid="0x2348">
    <title>Minimum Possible AFR Request</title>
    <CATEGORYMEM index="0" category="12" />
    <CATEGORYMEM index="1" category="56" />
    <EMBEDDEDDATA mmedtypeflags="0x02" mmedaddress="0x19156" mmedelementsizebits="8" mmedmajorstridebits="0" mmedminorstridebits="0" />
    <datatype>28</datatype>
    <unittype>0</unittype>
    <DALINK index="0" />
    <MATH equation="0.114843.375 * X">
      <VAR id="X" />
    </MATH>
  </XDFCONSTANT>

**Comment by allyouaskfor** [comment]
I appreciate that information. Thanks for looking over it. The XDF is not one that I created myself but seeing that the issue is within the XDF, I will create a new one containing only the variables required to use ME7Tuner. I'll test that out on my Macbook as soon as i can. Is there anything else I can do to help?

**Comment by KalebKE** [comment]
@allyouaskfor 

I do think I have the linking working, but I am having a hard time testing it due to the bad data in some of the unrelated tables. If you could get me a cleaned up (and potentially narrower) version of the XDF if would be helpful.

**Comment by run4x** [comment]
@KalebKE could you test the decimal separator (regional settings) issue with stock [551K](https://files.s4wiki.com/stock/8D0907551K.bin) bin and this short xdf attached?
[551K-me7tuner.zip](https://github.com/KalebKE/ME7Tuner/files/8654095/551K-me7tuner.zip)
Can you open all tabs and use the functionality as expected?
I can set the configuration, but cannot use the app at all.

**Comment by KalebKE** [comment]
@run4x 

I have defaulted the locale to English in https://github.com/KalebKE/ME7Tuner/issues/19. 

Release: https://github.com/KalebKE/ME7Tuner/releases/tag/v1.0.5

**Comment by KalebKE** [comment]
@allyouaskfor 

I am still working on your issue. I have to reverse engineer some bit fields from tuner pro to handle the matrix transformations correctly and I haven't found the time yet, but hopefully this weekend I will get a chance to work on it.

**Comment by allyouaskfor** [comment]
I appreciate all the work you're putting into this. Sorry that I haven't gotten you a slimmer XDF yet. I've been busy with work but I do still have the intention on getting that done. Thank you.
