### ISSUE TITLE
Does not work fully

### ISSUE THREAD

**Issue by kaplis117** [KalebKE/ME7Tuner#2]
Awesome job but program does not work fully on windows 10.
.jar file \model\kfldimx is missing Kfldimx.class. After placing file in location, program opens but many menus have inaccessible charts/ missing charts.
Bitdefender flags it as virus.
![2](https://user-images.githubusercontent.com/58876751/105774819-73df7e00-5f6e-11eb-98c6-f4476c88b9e3.jpg)
![1](https://user-images.githubusercontent.com/58876751/105774824-74781480-5f6e-11eb-832e-7133c81cf6d8.jpg)
![4](https://user-images.githubusercontent.com/58876751/105774825-7510ab00-5f6e-11eb-99ac-596e4591bf49.jpg)
![3](https://user-images.githubusercontent.com/58876751/105774826-7510ab00-5f6e-11eb-82dc-7299ef3842d2.jpg)

**Comment by KalebKE** [comment]
Hi,

What is your monitor size and screen resolution? I can't seem to reproduce this easily.

I will also start signing the JAR files. It won't keep BitDefender from flagging it, but at least folks can determine that I built it.

**Comment by kaplis117** [comment]
Im using laptop 15.6 inch (1366x768)
