### ISSUE TITLE
me7tuner not start with java

### ISSUE THREAD

**Issue by taoloo897** [KalebKE/ME7Tuner#22]
Hi. I try to start ME7Tuner_v1.0.5.jar but receive an error:
a jni error has occurred please check your installation and try again
Thanks in advance

**Comment by KalebKE** [comment]
@taoloo897 

Update Java to the latest version.

**Comment by taoloo897** [comment]
Thanks. I tried with new version. I tried with clear instalation and removed old versions. tryed with reboot too. Sytem is win10 64 bit.
Downloaded ME7Tuner_v1.0.5.jar and have 
"**a jni error has occurred please check your installation and try again**
ME7Tuner_v0.5.jar starts but when i goes on tabs from upstairs of window .....not works and no refresh.
Must install something additionals packages ?
Thanks again.

**Comment by KalebKE** [comment]
@taoloo897 

So it works with jdk 17 and not with jdk 18?

I haven't tried jdk 18 yet, but usually these problems occur going the other way... e.g compiled with jdk 17 but running against jdk 8 won't work.

**Comment by taoloo897** [comment]
jdk 17 is what i found quickky.
I had installed only JavaSetup8u333 before install jdk 17 and v1.0.5 not work. 
After i installed jdk 17 works ok.
