### ISSUE TITLE
My config causing error at launch

### ISSUE THREAD

**Issue by RENOxDECEPTION** [KalebKE/ME7Tuner#24]
How do you remove all preferences or where are they stored so I can manually remove them?

**Comment by KalebKE** [comment]
@RENOxDECEPTION 

Should be main menu bar -> preferences -> reset preferences.

If that doesn't work please post your config so I can reproduce and fix the issue.

**Comment by RENOxDECEPTION** [comment]
The program crashes on opening, i can't even access that anymore. I think I loaded a bad XDF

**Comment by KalebKE** [comment]
@RENOxDECEPTION 

Can you attach your XDF and bin file?
