### ISSUE TITLE
Cross compatibility 

### ISSUE THREAD

**Issue by JocelynS1996** [KalebKE/ME7Tuner#25]
Hey I've been looking for a year to find a program like this. I'm not a Audi/vw guy, I'm a Volvo guy and I HAVE the ME7.0.1, would this program work the the ME7.0.1 with minor alterations?

**Comment by KalebKE** [comment]
@JocelynS1996 

If ME7Tuner supports the maps you need then it should "just work" assuming you have an XDF to define the location of the maps.
