### ISSUE TITLE
Invalid Registry Entries for file_path_key ?

### ISSUE THREAD

**Issue by tightmopedman** [KalebKE/ME7Tuner#27]
When I open the program and load a .bin and .xdf the top bar text indicates that the file is loaded. However, when I choose 'Select Definition', even though a valid entry is found in the .xdf, selecting it does nothing. If I go to another window, like KFMIOP, at the bottom it says 'No Definition Selected'. 

If I close the program, I can't open it again and I get a whole host of errors, but I think the relevant one is this:
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at data.preferences.bin.BinFilePreferences.registerObserver(BinFilePreferences.java:44)
```

Going to the registry value Computer\HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\data.preferences.bin./Bin/File/Preferences, I find that the file_path_key is:
/C:///M/E7/Tuner//15.bin
The location of '15.bin' on my computer is:
C:\ME7Tuner\15.bin
The same sort of formatting is also present for the .xdf selection.
Computer\HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\data.preferences.xdf./Xdf/File/Preferences
/C:///M/E7/Tuner//551/M.xdf

I don't know anything about Java, but based on my conversations with ChatGPT, the formatting should be:
C:\\ME7Tuner\\551M.xdf
However, after manually replacing the registry keys with the above formatting, ME7Tuner still won't open.

If I delete all the keys created by ME7Tuner in Computer\HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\ from the registry I can restart the program, but all errors re-occur if I try loading a .bin again.

I have tried JDK 17 and 20 with the same results.

**Comment by KalebKE** [comment]
Hi, 

Could you provide an example of your XDF and binary?

**Comment by tightmopedman** [comment]
https://drive.google.com/open?id=1Vw97d0EU8nNEDDOZy2ZHS10mFMARi3Ad&authuser=tightmopedman9%40gmail.com&usp=drive_fs

https://drive.google.com/open?id=1VuRYMaYKSN_6Vy9a7K4fcYWvVPouZ3Us&authuser=tightmopedman9%40gmail.com&usp=drive_fs

**Comment by tightmopedman** [comment]
If use the following .xdf the problem doesn't occur.
https://drive.google.com/file/d/19QZDKEQBo9k1ERNzDUJWQSnImws4YrPT/view?usp=sharing
