### ISSUE TITLE
Noob question.

### ISSUE THREAD

**Issue by Arturona96** [KalebKE/ME7Tuner#29]
Hello,
Iv got a noob question. How to run your app? Do I need any additional software to run your project?

**Comment by mike65italy65** [comment]
same question. How do you use the program? Thank you.

**Comment by zCruuz** [comment]
Hi, what is the os you are running? it has been a while for me...
Win10/11 
-> install Java (i currently use Java 8 update 361)  
-> switch to us keyboard layout (dont know if still necessary)
-> open me7tuner 
->load bin and xdf in the top left corner

**Comment by Pytlok** [comment]
To anyone still interested, i managed to make it work. You need to download JAVA 17, and using CMD type java -jar (paste here path to the file, eg. C:\user\yourusername\downloads\me7tuner.jar, of course your path may vary depending where you saved it)

**Comment by iLimitlessi** [comment]
> To anyone still interested, i managed to make it work. You need to download JAVA 17, and using CMD type java -jar (paste here path to the file, eg. C:\user\yourusername\downloads\me7tuner.jar, of course your path may vary depending where you saved it). Or instead copying whole path, you can drag the file to cmd prompt and it will automatically do it for you


It dosn`t work for me. I have downloaded Java 17, used CMD comand java -jar and pasted location path.
BTW afrt i have Unziping ME7Tuner i dont have me7tuner.JAR extension its a ME7Tuner.iml file i have. Can some on hlpm to make this work pls?
